env:
  es6: true
  node: true
  mocha: true

parserOptions:
  #ecmaVersion: 2015 (6)
  #ecmaVersion: 2016 (7) (node 6)
  #ecmaVersion: 2017 (8) (node 8)
  ecmaVersion: 2017
  #ecmaVersion: 2018 (9) (node 10)
  #ecmaVersion: 2019 (10) (node 12)
  #ecmaVersion: 2020 (11) (node 14)

root: true

rules:
  dot-notation: 2
  indent: [2, 4, {"SwitchCase": 1}]
  one-var: [2, "never"]
  keyword-spacing: [2, {"overrides": { }} ]
  no-trailing-spaces: [2, { "skipBlankLines": false }]
  no-delete-var: 2
  no-label-var: 2
  no-shadow: 2
  no-console: 0
  semi-style: [error, last]
  prefer-template: "warn"
  no-unneeded-ternary: 1

extends: ["eslint:recommended"]