{
  "env": {
    "es6": true,
    "node": true,
    "mocha": true
  },
  "extends": [
    "eslint:recommended"
  ],
  "rules": {
    "dot-notation": 2,
    "indent": [2, 4, {"SwitchCase": 1}],
    "one-var": [2, "never"],
    "keyword-spacing": [2, {"overrides": {
      }}],
    "no-trailing-spaces": [2, { "skipBlankLines": false }],
    "no-delete-var": 2,
    "no-label-var": 2,
    "no-shadow": 2,
    "no-console": 0
  }
}