language: node_js

node_js:
    - "13"
    - "12"
    - "10"
    #- "8"    Maintenance ended 2019-12-31
    #- "6"
    #- "4"    Maintenance ending 2018-04-30
    #- iojs   No longer maintained
    #- "0.12" Maintenance ending 2017-04-01
    #- "0.10" Maintenance ending 2016-10-01
    #- "0.8"  Not supported by mocha
    #- "0.6"  Script works, tests don't

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run cover
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov
