name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1
        name: Checkout Code
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Run lintfix to catch errors caused by prettier
        run: npm run lintfix

      - name: Lint using eslint
        run: npm run lint

        env:
          CI: true
