
name: publish

on:
  push:
    branches:
      - master

env:
  node_version: 14

jobs:

  publish-gpr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        run: npm install

      - name: Run test suite
        run: npm run test

      - name: publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release
