
name: publish

on:
  push:
    branches:
      - master
    paths:
      - package.json

env:
  node_version: 18

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: ${{ env.node_version }}

      - name: npm install
        run: npm install

      - name: Run test suite
        run: npm run test

      - name: publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
